[package]
name = "openai_speech_to_speech"
version = "0.1.0"
edition = "2021"

[dependencies]
make87 = "*"
make87_messages = ">=0.2.2"
openai-api-rs = "6.0.3"
futures-util = "0.3.31"
tokio = "1.44.2"
tokio-tungstenite = "0.24.0"
futures-channel = "0.3.31"
serde_json = "1.0.140"
base64 = "0.22.1"
